server:
  port: 80
spring:
  datasource:
    url: jdbc:h2:~/im
    driver-class-name: org.h2.Driver
    username: sa
    password: 123456
    schema: classpath:db/schema.sql
    data: classpath:db/data.sql

  h2:
    console:
      path: /h2-console
      enabled: true

  jpa:
    database: h2
    show-sql: true
    hibernate:
      ddl-auto: update

  redis:
    host: localhost
    port: 6379

websocket:
  connector:
    server:
      readIdleSecond: 0
      writeIdleSecond: 0
      allIdleSecond: 360
      sendBuff: -1
      recvBuff: -1
      backlog: 500000
      bossThreads: 1
      connTimeoutMills: 10000
      soLinger: 0
      port: 8080
      reuseAddr: true
      useDirectBuffer: true
      useEpoll: true
      useMemPool: true
      userThreads: 50
      workerThreads: 0
      idleTimes: 5